# Generated by Django 5.2.7 on 2025-11-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0005_pedido_fecha_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='prendas',
        ),
        migrations.AddField(
            model_name='prenda',
            name='categorias',
            field=models.ManyToManyField(related_name='categoriasPrenda', to='tiendaApp.categoria'),
        ),
    ]
