# Generated by Django 4.2.7 on 2025-11-27 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0006_remove_categoria_prendas_prenda_categorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoPrenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=300)),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='tiendaApp.prenda')),
            ],
        ),
    ]
