# Generated by Django 5.2.7 on 2025-11-28 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0007_fotoprenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenda',
            name='foto',
        ),
    ]
