# Generated by Django 5.2.7 on 2025-11-28 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0008_remove_prenda_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantePrenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='tiendaApp.prenda')),
            ],
            options={
                'verbose_name': 'Variante',
                'verbose_name_plural': 'Variantes',
            },
        ),
    ]
