# Generated by Django 5.2.7 on 2025-12-01 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0009_varianteprenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='prendas',
        ),
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('carrito', 'Carrito'), ('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='carrito', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='tiendaApp.cliente'),
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tiendaApp.pedido')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_pedido', to='tiendaApp.varianteprenda')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Items de Pedido',
                'unique_together': {('pedido', 'variante')},
            },
        ),
    ]
