# Generated by Django 5.2.7 on 2025-12-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0011_sesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
