# Generated by Django 5.2.7 on 2025-12-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0012_alter_cliente_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='foto',
        ),
    ]
