# Generated by Django 5.2.7 on 2025-12-06 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0013_remove_cliente_direccion_remove_cliente_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenda',
            name='talla',
        ),
    ]
