# Generated by Django 5.2.7 on 2025-12-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0014_remove_prenda_talla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
