# Generated by Django 5.2.7 on 2025-12-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0015_alter_prenda_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
